nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

npmRegistries:
  //registrynpm.storefrontcloud.io/:
    npmAuthToken: '${NODE_AUTH_TOKEN}'
    npmAlwaysAuth: true

npmScopes:
  vsf-enterprise:
    npmRegistryServer: https://registrynpm.storefrontcloud.io
