name: Testing (Lighthouse CI)
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'apps/web/**'
      - 'lighthouserc.json'

jobs:
  lighthouse:
    name: Performance Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEFAULT_ENTERPRISE_TOKEN }}
        with:
          node-version-file: './.github/.node-version'
          cache: 'yarn'
          registry-url: https://registrynpm.storefrontcloud.io

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Build application
        run: yarn turbo run build --scope="web"

      - name: lighthouse mobile audit
        run: yarn lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          CNTF_SPACE: ${{ vars.CNTF_SPACE }}
          CNTF_TOKEN: ${{ secrets.CNTF_TOKEN }}
          CNTF_BRANCH: ${{ vars.CNTF_BRANCH }}
          SAPCC_OAUTH_URI: ${{ vars.SAPCC_OAUTH_URI }}
          SAPCC_OAUTH_CLIENT_ID: ${{ vars.SAPCC_OAUTH_CLIENT_ID }}
          SAPCC_OAUTH_CLIENT_SECRET: ${{ secrets.SAPCC_OAUTH_CLIENT_SECRET }}
          SAPCC_OAUTH_TOKEN_ENDPOINT: ${{ vars.SAPCC_OAUTH_TOKEN_ENDPOINT }}
          SAPCC_OAUTH_TOKEN_REVOKE_ENDPOINT: ${{ vars.SAPCC_OAUTH_TOKEN_REVOKE_ENDPOINT }}
          SAPCC_API_URI: ${{ vars.SAPCC_API_URI }}
          SAPCC_MEDIA_HOST: ${{ vars.SAPCC_MEDIA_HOST }}
          DEFAULT_BASE_SITE_ID: ${{ vars.DEFAULT_BASE_SITE_ID }}
          DEFAULT_CATALOG_ID: ${{ vars.DEFAULT_CATALOG_ID }}
          DEFAULT_CATALOG_VERSION: ${{ vars.DEFAULT_CATALOG_VERSION }}
          DEFAULT_LANGUAGE: ${{ vars.DEFAULT_LANGUAGE }}
          DEFAULT_CURRENCY: ${{ vars.DEFAULT_CURRENCY }}
          NUXT_PUBLIC_CLOUDINARY_CMS_URL: ${{ vars.NUXT_PUBLIC_CLOUDINARY_CMS_URL }}
